# Generated by Django 3.1.7 on 2021-03-05 20:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210305_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'hr'], label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('two_columns', wagtail.core.blocks.StructBlock([('position', wagtail.core.blocks.ChoiceBlock(choices=[('left', '70%-30%'), ('middle', '50%-50%'), ('right', '30%-70%')], label='Disposition des colonnes')), ('left_column', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-left', label='Colonne de gauche')), ('right_column', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Colonne de droite'))])), ('three_columns', wagtail.core.blocks.StructBlock([('left_column', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-left', label='Colonne de gauche')), ('middle_column', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Colonne centrale')), ('right_column', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Colonne de droite'))]))], null=True, verbose_name='Contenu'),
        ),
    ]
