# Generated by Django 3.1.7 on 2021-03-06 16:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0004_auto_20210305_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'hr'], label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('two_columns', wagtail.core.blocks.StructBlock([('position', wagtail.core.blocks.ChoiceBlock(choices=[('left', '70%-30%'), ('middle', '50%-50%'), ('right', '30%-70%')], label='Disposition des colonnes')), ('left_column', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-left', label='Colonne de gauche')), ('right_column', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Colonne de droite'))])), ('three_columns', wagtail.core.blocks.StructBlock([('left_column', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-left', label='Colonne de gauche')), ('middle_column', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Colonne centrale')), ('right_column', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock())], icon='arrow-right', label='Colonne de droite'))]))], verbose_name='Contenu')),
            ],
            options={
                'verbose_name': 'Page classique',
            },
            bases=('wagtailcore.page',),
        ),
    ]
